source_directory: 'F:\konstantin.grotov\konstantin.grotov\genetic-acoustics-materials\empty_project\empty_project.mph'
tmp_directory: 'F:\konstantin.grotov\konstantin.grotov\genetic-acoustics-materials\samples\tmp.mph'
target_directory: 'F:\konstantin.grotov\konstantin.grotov\genetic-acoustics-materials\samples\sample1.mph'
images_directory: 'F:\konstantin.grotov\konstantin.grotov\genetic-acoustics-materials\images'